### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by skoften** [TopShelfCraft/Wordsmith-Docs#4] opened 2018-07-22 16:32 UTC
![screen shot 2018-07-22 at 18 31 38](https://user-images.githubusercontent.com/1286410/43047811-8998b58c-8ddd-11e8-9a3c-fcb75d626e1f.jpg)

Craft CMS 3.0.16.1
PHP 7.0.30

**Comment by michaelrog** [comment] 2018-07-22 19:46
This is a duplicate of: https://github.com/TopShelfCraft/Wordsmith/issues/6

**Closed by michaelrog** 2018-07-22 19:46 UTC
